name: Lint

on:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Lint backend
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6
          only-new-issues: true
